# Use Visual Studio Code REST Client to run them

POST http://localhost:5000/api/frauds/detect
Content-Type: application/json

{
    "Id": "{{$guid}}"
}

###

POST https://mock-fraud-detection.azurewebsites.net/api/frauds/detect
Content-Type: application/json

{
    "Id": "{{$guid}}"
}